# HTTP Server
server:
  port: 8761

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/drobled/springcloud

  # Spring properties in case you use different profiles
  profiles:
    active: dev
  eureka:
    client:
      #telling the server not to register himself in the service registry
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync